# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dWog2fydGzWC1EWXG1RHevHfKZrDItNx

#***Первое задание***
"""

library(ggplot2)
library(readxl)
#library(Cairo)
library(scales)
library(dplyr)
library(tidyverse)
library(lubridate)
df1 <- read.csv("howpop_train.csv")
head(df1)

df1$published = as.character(df1$published)
df1$year <- as.numeric(substring(df1$published, 1, 4))
df1$month <- as.numeric(substring(df1$published, 6, 7))
df1$day <- as.numeric(substring(df1$published, 9, 10))
df1$hour <- as.numeric(substring(df1$published, 12, 13))
y_2015 <- subset(df1, year == 2015)
y_2016 <- subset(df1, year == 2016)
y_2015_03 <- subset(y_2015, month == 3)
y_2015_04 <- subset(y_2015, month == 4)
y_2016_03 <- subset(y_2016, month == 3)
y_2016_04 <- subset(y_2016, month == 4)
m <- rbind(c(nrow(y_2015_03), nrow(y_2016_03)), c(nrow(y_2015_04), nrow(y_2016_04)))
colnames(m) <- c("march", "april")
rownames(m) <- c(2015, 2016)
barplot(m, ylab="number", legend = rownames(m), beside=TRUE, col = topo.colors(2),  border = "black")

"""#***Второе задание***
#Выберите один или несколько вариантов: 
#1) Один или несколько дней сильно выделяются из общей картины. 
#2) На хабре всегда больше статей, чем на гиктаймсе.
#3) По субботам на гиктаймс и на хабрахабр публикуют примерно одинаковое число статей.

# ***Первое высказывание***
"""

library(ggplot2)
library(readxl)
#library(Cairo)
library(scales)
library(dplyr)
library(tidyverse)
library(lubridate)
df1 <- read.csv("howpop_train.csv")

library(data.table)
df1 <- read.csv("howpop_train.csv")
df1$published = as.character(df1$published)
df1$year <- as.numeric(substring(df1$published, 1, 4))
df1$month <- as.numeric(substring(df1$published, 6, 7))
df1$day <- as.numeric(substring(df1$published, 9, 10))
df1$hour <- as.numeric(substring(df1$published, 12, 13))
y_2015 <- subset(df1, year == 2015)
y_2015_03 <- subset(y_2015, month == 3)
y_2015_03_days <- y_2015_03$day
table <- data.table(y_2015_03_days)
grouped_table <- table[, .N, by = names(table)]
data <- grouped_table$N
m = rbind(c(data[1:31]))
colnames(m) = c("1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31")
rownames(m) = c("number of texts")
barplot(m, ylab=rownames(m), xlab="days", beside=TRUE, col = rainbow(31),  border = "black")
#barplot(m, ylab=rownames(m), xlab="days", beside=TRUE, col = "#99FFFF",  border = "black")

"""# ***Второе высказывание***"""

library(data.table)
df1 <- read.csv("howpop_train.csv")
df1$published = as.character(df1$published)
df1$year <- as.numeric(substring(df1$published, 1, 4))
df1$month <- as.numeric(substring(df1$published, 6, 7))
df1$day <- as.numeric(substring(df1$published, 9, 10))
df1$hour <- as.numeric(substring(df1$published, 12, 13))
y_2015 <- subset(df1, year == 2015)
y_2015_03 <- subset(y_2015, month == 3)
y_2015_03_habr <- subset(y_2015_03, domain == "habrahabr.ru")
y_2015_03_geek <- subset(y_2015_03, domain == "geektimes.ru")
y_2015_03_habr_days <- y_2015_03_habr$day
table_habr <- data.table(y_2015_03_habr_days)
grouped_table_habr <- table_habr[, .N, by = names(table_habr)]
data_habr <- grouped_table_habr$N
y_2015_03_geek_days <- y_2015_03_geek$day
table_geek <- data.table(y_2015_03_geek_days)
grouped_table_geek <- table_geek[, .N, by = names(table_geek)]
data_geek <- grouped_table_geek$N
m = rbind(c(data_geek[1:31]), c(data_habr[1:31]))
colnames(m) = c("1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31")
rownames(m) = c("geektimes.ru", "habrahabr.ru")
barplot(m, ylab="Number of texts on each site", xlab="days", beside=TRUE, legend = rownames(m), col = topo.colors(2),  border = "black")

"""# ***Третье высказывание***"""

df1 <- read.csv("howpop_train.csv")
df1$published = as.character(df1$published)
df1$year <- as.numeric(substring(df1$published, 1, 4))
df1$month <- as.numeric(substring(df1$published, 6, 7))
df1$day <- as.numeric(substring(df1$published, 9, 10))
df1$hour <- as.numeric(substring(df1$published, 12, 13))

Saturdays <- function(year, month) {
    days <- as.POSIXlt(paste(year, month, 1:31, sep="-"), format="%Y-%m-%j")
    Std <- (days[days$wday==6])
    Std[!is.na(Std)]
}
a <- (Saturdays(2015, 3))
y_2015 <- subset(df1, year == 2015)
y_2015_03 <- subset(y_2015, month == 3)
y_2015_03_habr <- subset(y_2015_03, y_2015_03$domain  == "habrahabr.ru")
y_2015_03_geek <- subset(y_2015_03, y_2015_03$domain  == "geektimes.ru")

first_saturday <- as.character(a[1])
day1 <- as.numeric(substring(first_saturday, 9, 10))

second_saturday <- as.character(a[2])
day2 <- as.numeric(substring(second_saturday, 9, 10))


third_saturday <- as.character(a[3])
day3 <- as.numeric(substring(third_saturday, 9, 10))

fourth_saturday <- as.character(a[4])
day4 <- as.numeric(substring(fourth_saturday, 9, 10))

first_saturday_habr <- nrow(subset(y_2015_03_habr, y_2015_03_habr$day == day1))
second_saturday_habr <- nrow(subset(y_2015_03_habr, y_2015_03_habr$day == day2))
third_saturday_habr <- nrow(subset(y_2015_03_habr, y_2015_03_habr$day == day3))
fourth_saturday_habr <- nrow(subset(y_2015_03_habr, y_2015_03_habr$day == day4))

first_saturday_geek <- nrow(subset(y_2015_03_geek, y_2015_03_geek$day == day1))
second_saturday_geek <- nrow(subset(y_2015_03_geek, y_2015_03_geek$day == day2))
third_saturday_geek <- nrow(subset(y_2015_03_geek, y_2015_03_geek$day == day3))
fourth_saturday_geek <- nrow(subset(y_2015_03_geek, y_2015_03_geek$day == day4))

m = rbind(c(first_saturday_geek, second_saturday_geek, third_saturday_geek, fourth_saturday_geek),
c(first_saturday_habr, second_saturday_habr, third_saturday_habr, fourth_saturday_habr))
colnames(m) = c("07.03.2015", "14.03.2015", "21.03.2015", "28.03.2015")
rownames(m) = c("geektimes.ru", "habrahabr.ru")
barplot(m, ylab="Number of texts on each site", xlab="Dates", beside=TRUE, legend = rownames(m), col = topo.colors(2),  border = "black")

library(data.table)
df1 <- read.csv("howpop_train.csv")
df1$published = as.character(df1$published)
df1$year <- as.numeric(substring(df1$published, 1, 4))
df1$month <- as.numeric(substring(df1$published, 6, 7))
df1$day <- as.numeric(substring(df1$published, 9, 10))
df1$hour <- as.numeric(substring(df1$published, 12, 13))

Saturdays <- function(year, month) {
    days <- as.POSIXlt(paste(year, month, 1:31, sep="-"), format="%Y-%m-%j")
    Std <- (days[days$wday==6])
    Std[!is.na(Std)]
}
a <- (Saturdays(2015, 3))
y_2015 <- subset(df1, year == 2015)
y_2015_03 <- subset(y_2015, month == 3)

saturdays <- as.character(a)
saturdays <- as.numeric(substring(a, 9, 10))

y_2015_03_habr <- subset(y_2015_03, domain == "habrahabr.ru")
y_2015_03_geek <- subset(y_2015_03, domain == "geektimes.ru")

#a <- y_2015_03_habr$day
#b <- data.table(a)
#c <- data.table(y_2015_03_habr$day)[, .N, by = names(data.table(y_2015_03_habr$day))]
d <- data.table(y_2015_03_habr$day)[, .N, by = names(data.table(y_2015_03_habr$day))]$N

#a1 <- y_2015_03_geek$day
#b1 <- data.table(a1)
#c1 <- data.table(y_2015_03_geek$day)[, .N, by = names(data.table(y_2015_03_geek$day))]
d1 <- data.table(y_2015_03_geek$day)[, .N, by = names(data.table(y_2015_03_geek$day))]$N
d[saturdays]
d1[saturdays]
m = rbind(c(d1[saturdays]), c(d[saturdays]))
colnames(m) = c("07.03.2015", "14.03.2015", "21.03.2015", "28.03.2015")
rownames(m) = c("geektimes.ru", "habrahabr.ru")
barplot(m, ylab="Number of texts on each site", xlab="Dates", beside=TRUE, legend = rownames(m), col = topo.colors(2),  border = "black")

library(data.table)
df1 <- read.csv("howpop_train.csv")
df1$published = as.character(df1$published)
df1$year <- as.numeric(substring(df1$published, 1, 4))
df1$month <- as.numeric(substring(df1$published, 6, 7))
df1$day <- as.numeric(substring(df1$published, 9, 10))
df1$hour <- as.numeric(substring(df1$published, 12, 13))
df1$published <- as.Date(df1$published)
df1$weekday = weekdays(df1$published)
y_2015_03_habr_saturday <- subset(df1, year == 2015 & month == 3 & domain == "habrahabr.ru" & weekday == "Saturday")
y_2015_03_geek_saturday <- subset(df1, year == 2015 & month == 3 & domain == "geektimes.ru" & weekday == "Saturday")
y_2015_03_habr_saturday_dates <- y_2015_03_habr_saturday$day
table_habr <- data.table(y_2015_03_habr_saturday_dates)
grouped_table_habr <- table_habr[, .N, by = names(table_habr)]
data_habr <- grouped_table_habr$N
y_2015_03_geek_saturday_dates <- y_2015_03_geek_saturday$day
table_geek <- data.table(y_2015_03_geek_saturday_dates)
grouped_table_geek <- table_geek[, .N, by = names(table_geek)]
data_geek <- grouped_table_geek$N
m = rbind(c(data_geek[1:4]), c(data_habr[1:4]))
colnames(m) = c("07.03.2015", "14.03.2015", "21.03.2015", "28.03.2015")
rownames(m) = c("geektimes.ru", "habrahabr.ru")
barplot(m, ylab="Number of texts on each site", xlab="Dates", beside=TRUE, legend = rownames(m), col = topo.colors(2),  border = "black")

"""# ***Третье задание***

#1) Больше всего просмотров набирают статьи, опубликованные в 12 часов дня
#2) Больше всего просмотров набирают статьи, опубликованные в 6 часов утра
#3) У опубликованных в 10 утра постов больше всего комментариев
#4) Максимальное число комментариев на гиктаймсе набрала статья, опубликованная в 9 часов вечера.
#5) На хабре дневные статьи комментируют чаще, чем вечерние

# ***Первое высказывание***
"""

library(janitor)
library(ggplot2)
library(lubridate)
df1 <- read.csv("howpop_train.csv")
df1$published = as.character(df1$published)
df1$year <- as.numeric(substring(df1$published, 1, 4))
df1$month <- as.numeric(substring(df1$published, 6, 7))
df1$day <- as.numeric(substring(df1$published, 9, 10))
df1$hour <- as.numeric(substring(df1$published, 12, 13))
df1 %>%
  group_by(hour = hour(published)) %>%
  summarise(views = sum(views)) %>% 
  ggplot(aes(x = hour, y = views))+
  geom_line(color = "#CC0033", size = 1.25) +
  geom_point(size = 3)

data3 <- read.csv("howpop_train.csv", header = TRUE, sep = ',')
to.remove <- c('views_lognorm', 'favs_lognorm', 'comments_lognorm') 
data3 <- data3[, !colnames(data3) %in% to.remove]
library(janitor)
library(ggplot2)
library(lubridate)

data3 %>%
  group_by(hour = hour(published)) %>%
  summarise(views = sum(views)) %>% 
  ggplot(aes(x = hour, y = views))+
  geom_col(color = "#99FFFF")+
  geom_line(color = "#CC0033", size = 1.25) +
  geom_point(size = 2)
  #geom_line(color = "#0033FF")color = "#CC3300"

"""# ***Второе высказывание***"""

library(janitor)
library(ggplot2)
library(lubridate)
df1 <- read.csv("howpop_train.csv")
df1$published = as.character(df1$published)
df1$year <- as.numeric(substring(df1$published, 1, 4))
df1$month <- as.numeric(substring(df1$published, 6, 7))
df1$day <- as.numeric(substring(df1$published, 9, 10))
df1$hour <- as.numeric(substring(df1$published, 12, 13))
df1 %>%
  group_by(hour = hour(published)) %>%
  summarise(views = sum(views)) %>% 
  ggplot(aes(x = hour, y = views))+
  geom_line(color = "#CC3300") +
  geom_point(size = 2)

library(janitor)
library(ggplot2)
library(lubridate)
df1 <- read.csv("howpop_train.csv")
df1$published = as.character(df1$published)
df1$year <- as.numeric(substring(df1$published, 1, 4))
df1$month <- as.numeric(substring(df1$published, 6, 7))
df1$day <- as.numeric(substring(df1$published, 9, 10))
df1$hour <- as.numeric(substring(df1$published, 12, 13))
df1 %>%
  group_by(hour = hour(published)) %>%
  summarise(views = sum(views)) %>%
  ggplot(aes(x = hour, y = views))+
  geom_col(color = "#99FFFF")

"""# ***Третье высказывание***"""

library(janitor)
library(ggplot2)
library(lubridate)
df1 <- read.csv("howpop_train.csv")
df1$published = as.character(df1$published)
df1$year <- as.numeric(substring(df1$published, 1, 4))
df1$month <- as.numeric(substring(df1$published, 6, 7))
df1$day <- as.numeric(substring(df1$published, 9, 10))
df1$hour <- as.numeric(substring(df1$published, 12, 13))
df1 %>%
  group_by(hour = hour(published)) %>%
  summarise(comments = sum(comments)) %>% 
  ggplot(aes(x = hour, y = comments))+
  geom_line(color = "#CC0033", size = 1.25) +
  geom_point(size = 3)

data3 <- read.csv("howpop_train.csv", header = TRUE, sep = ',')
to.remove <- c('views_lognorm', 'favs_lognorm', 'comments_lognorm') 
data3 <- data3[, !colnames(data3) %in% to.remove]
library(janitor)
library(ggplot2)
library(lubridate)

data3 %>%
  group_by(hour = hour(published)) %>%
  summarise(comments = sum(comments)) %>% 
  ggplot(aes(x = hour, y = comments))+
  geom_col(color = "#99FFFF")

"""# ***Четвёртое высказывание***"""

library(janitor)
library(ggplot2)
library(lubridate)
df1 <- read.csv("howpop_train.csv")
df1$published = as.character(df1$published)
df1$year <- as.numeric(substring(df1$published, 1, 4))
df1$month <- as.numeric(substring(df1$published, 6, 7))
df1$day <- as.numeric(substring(df1$published, 9, 10))
df1$hour <- as.numeric(substring(df1$published, 12, 13))
df2 <- subset(df1, domain == "geektimes.ru")
df2 %>%
  group_by(hour = hour(published)) %>%
  summarise(comments = max(comments)) %>% 
  ggplot(aes(x = hour, y = comments))+
  geom_line(color = "#CC0033", size = 1.25) +
  geom_point(size = 3)

data3 <- read.csv("howpop_train.csv", header = TRUE, sep = ',')
to.remove <- c('views_lognorm', 'favs_lognorm', 'comments_lognorm') 
data3 <- data3[, !colnames(data3) %in% to.remove]
library(janitor)
library(ggplot2)
library(lubridate)
data3 <- subset(data3, domain == "geektimes.ru")
data3 %>%
  group_by(hour = hour(published)) %>%
  summarise(comments = max(comments)) %>% 
  ggplot(aes(x = hour, y = comments))+
  geom_col(color = "#99FFFF")

"""# ***Пятое высказывание***"""

library(janitor)
library(ggplot2)
library(lubridate)
df1 <- read.csv("howpop_train.csv")
df1$published = as.character(df1$published)
df1$year <- as.numeric(substring(df1$published, 1, 4))
df1$month <- as.numeric(substring(df1$published, 6, 7))
df1$day <- as.numeric(substring(df1$published, 9, 10))
df1$hour <- as.numeric(substring(df1$published, 12, 13))
df2 <- subset(df1, domain == "habrahabr.ru")
df2 %>%
  group_by(hour = hour(published)) %>%
  summarise(comments = mean(comments)) %>% 
  ggplot(aes(x = hour, y = comments))+
  geom_line(color = "#CC0033", size = 1.25) +
  geom_point(size = 3)

data3 <- read.csv("howpop_train.csv", header = TRUE, sep = ',')
to.remove <- c('views_lognorm', 'favs_lognorm', 'comments_lognorm') 
data3 <- data3[, !colnames(data3) %in% to.remove]
library(janitor)
library(ggplot2)
library(lubridate)
data3 <- subset(data3, domain == "habrahabr.ru")
data3 %>%
  group_by(hour = hour(published)) %>%
  summarise(comments = mean(comments)) %>%
  ggplot(aes(x = hour, y = comments))+
  geom_col(color = "#99FFFF")

"""# 4. Кого из топ-20 авторов чаще всего минусуют?
#1) @Mordatyj
#2) @Mithgol
#3) @alizar
#4) @ilya42
"""

df1 <- read.csv("howpop_train.csv")
df1 <- na.omit(df1)
Mordatyj <- mean(df1[df1["author"] == '@Mordatyj', 'votes_minus'])
Mithgol <- mean(df1[df1["author"] == '@Mithgol', 'votes_minus'])
alizar <- mean(df1[df1["author"] == '@alizar', 'votes_minus'])
ilya42 <- mean(df1[df1["author"] == '@ilya42', 'votes_minus'])
m = rbind(c(Mordatyj, Mithgol, alizar, ilya42))
colnames(m) = c("Mordatyj", "Mithgol", "alizar", "ilya42")
rownames(m) = c("authors")
barplot(m, ylab="Comments", xlab="Authors", col = topo.colors(4), border = "black", beside=TRUE)

"""# 5. Сравните субботы и понедельники.
# Правда ли, что по субботам авторы пишут в основном днём, а по понедельникам пишут в основном вечером?
"""

library(data.table)
df1 <- read.csv("howpop_train.csv")
df1$published = as.character(df1$published)
df1$year <- as.numeric(substring(df1$published, 1, 4))
df1$month <- as.numeric(substring(df1$published, 6, 7))
df1$day <- as.numeric(substring(df1$published, 9, 10))
df1$hour <- as.numeric(substring(df1$published, 12, 13))
df1$published <- as.Date(df1$published)
df1$weekday = weekdays(df1$published)
Saturdays <- subset(df1, weekday == "Saturday")
Mondays <- subset(df1, weekday == "Monday")
Saturdays_hours <- as.integer(Saturdays$hour)
table_saturday <- data.table(Saturdays_hours)
table_saturday <- table_saturday[order(table_saturday, decreasing = FALSE),] 
grouped_table_saturday <- table_saturday[, .N, by = names(table_saturday)]
data_saturday <- grouped_table_saturday$N
Mondays_hours <- as.integer(Mondays$hour)
table_monday <- data.table(Mondays_hours)
table_monday <- table_monday[order(table_monday, decreasing = FALSE),]
grouped_table_monday <- table_monday[, .N, by = names(table_monday)]
data_monday <- grouped_table_monday$N
m = rbind(c(data_monday[1:24]), c(data_saturday[1:24]))
colnames(m) <- c("0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23")
rownames(m) <- c("Mondays", "Saturdays")
barplot(m, ylab="Number of texts by hour on mondays and saturdays", xlab="hours", beside=TRUE, legend = rownames(m), col = topo.colors(2),  border = "black")
